version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fonoma-network

  fastapi:
    container_name: fonomajobs
    image: yadisnel/fonomajobs:v1.2
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - fonoma-network
    depends_on:
      - redis

networks:
  fonoma-network: